#First App

apiVersion: v1
kind: Service
metadata:
  name: wuservice
spec:
 type: NodePort
 ports:
  - port: 80
    nodePort: 31001 # 30000-32767 kube-apiserver --service-node-port-range
    name : wuappport
    protocol: TCP
 selector:
   app: wuapp
 